=== Jucyliana/WDS2.0/schemas/options.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Options Schema",
  "description": "Schema for options.json files containing unit/model customization options",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Id", "Name", "Type"],
    "properties": {
      "Id": {
        "type": "string",
        "description": "Unique identifier for the option"
      },
      "Name": {
        "type": "string",
        "description": "Name of the option"
      },
      "Type": {
        "type": "integer",
        "minimum": 0,
        "maximum": 7,
        "description": "Type of option - determines how it affects units/models (0=SwapUnit, 1=ModifyItemOnAll, 2=ModifyItemOnBasic, 3=SwapBasic, 4=ModifyItemOnSingle, 5=SwapSingle, 6=AddSingle, 7=AddExtras)"
      },
      "ItemsToAdd": {
        "type": "array",
        "description": "Array of items to add (statlines, rules, equipment, etc.)",
        "items": {
          "type": "object",
          "required": ["Id"],
          "properties": {
            "Id": {
              "type": "string",
              "description": "ID of the item to add"
            },
            "Info": {
              "type": "string",
              "description": "Optional additional information about the item"
            }
          },
          "additionalProperties": false
        }
      },
      "ExtraItems": {
        "type": "array",
        "description": "List of extra items (cards, units, etc.) associated with this option",
        "items": {
          "type": "object",
          "required": ["Id", "Type"],
          "properties": {
            "Id": {
              "type": "string",
              "description": "ID of the extra item. Just deployable items like cards, tokens, cardstacks or units for now, but could be extended to other types if needed"
            },
            "Type": {
              "type": "string",
              "enum": ["Unit", "Card", "Token", "Cardstack", "Rule", "Equipment", "Statline"],
              "description": "Type of the extra item"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  }
}

=== Jucyliana/WDS2.0/WAP/Dogs of War/options.json
[
  {
    "Id": "6e278d4d-16f6-4493-9888-bb25737d0bde",
    "Name": "Lucrezzia Belladonna",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_lucrezzia_belladonna_420630ff"
      }
    ]
  },
  {
    "Id": "eed84677-9e98-410b-837b-1014efd2697c",
    "Name": "Marco Colombo",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_marco_colombo_ccd44131"
      }
    ]
  },
  {
    "Id": "3de223a5-ec66-4d1e-bc1d-2f42f5ae4600",
    "Name": "Borgio the Besieger",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_borgio_the_besieger_79718451"
      }
    ]
  },
  {
    "Id": "fddd8f67-b8cf-4ece-b1cb-0f9ad7225416",
    "Name": "Lorenzo Lupo",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_lorenzo_lupo_efdb881b"
      }
    ]
  },
  {
    "Id": "a557f029-beee-4409-a621-5a8bfa58931e",
    "Name": "Lietpold the Black",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_lietpold_the_black_f415035e"
      }
    ]
  },
  {
    "Id": "e0ff0f1f-7ad7-42cf-8c0d-3d3a383c23fe",
    "Name": "Morgan Bernhardt",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_morgan_bernhardt_0c787fd0"
      }
    ]
  },
  {
    "Id": "89debb15-8aa8-4f38-ab24-0618b49c719a",
    "Name": "Ulli & Marquand",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_ulli_&_marquand_e33bff7d"
      }
    ]
  },
  {
    "Id": "f4e975e6-a30d-4951-88b6-b15cd28212d4",
    "Name": "Simius Gantt",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_simius_gantt_f905fd57"
      }
    ]
  },
  {
    "Id": "2df085d0-5fec-4654-94a4-c5d844fbf2aa",
    "Name": "Nicodemus",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_nicodemus_b4a1d2eb"
      }
    ]
  },
  {
    "Id": "1bce418c-5dd1-4365-b546-ba13d580558c",
    "Name": "Mydas the Mean",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_mydas_the_mean_273776ec"
      }
    ]
  },
  {
    "Id": "6f3c5b71-100a-41f7-893b-f61541ae43af",
    "Name": "Marianna Chevaux",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_marianna_chevaux_ba036442"
      }
    ]
  },
  {
    "Id": "2424e910-72d7-47ea-9368-cdc5e04628cb",
    "Name": "Aenur",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_aenur_09190806"
      }
    ]
  },
  {
    "Id": "3f9144ab-0675-4ba1-ae83-398c4c222768",
    "Name": "Johann the Knife",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_johann_the_knife_f60bbcad"
      }
    ]
  },
  {
    "Id": "83d13d90-ca37-4f53-82fb-fef9d998f803",
    "Name": "Leonardo Da Miragliano",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rule_leonardo_da_miragliano_e92322b3"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/40k/Black Templars/options.json
[
  {
    "Id": "options_1773681639806",
    "Name": "Combi-weapon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "a668-202f-eb7b-4a41"
      }
    ]
  },
  {
    "Id": "options_1773682310664",
    "Name": "Pyre Pistol",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "62bd-9f6-bc09-5fd"
      }
    ]
  },
  {
    "Id": "options_1773682344849",
    "Name": "Neophyte firearm & Close combat weapon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "6b66-6f8e-2809-dfea"
      },
      {
        "Id": "equipment_1773681967394"
      }
    ]
  },
  {
    "Id": "options_1773682409165",
    "Name": "Heavy bolt pistol & Astartes chainsword",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1773682259173"
      },
      {
        "Id": "equipment_1773682152566"
      }
    ]
  },
  {
    "Id": "options_1773682498090",
    "Name": "Heavy bolt pistol & Power fist",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1773682259173"
      },
      {
        "Id": "equipment_1773682571067"
      }
    ]
  },
  {
    "Id": "options_1773682608944",
    "Name": "Pyreblaster",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1764333773012"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/40k/Necrons/options.json
[
  {
    "Id": "options_1770894215937",
    "Name": "Tesla Cannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "b10e-f630-e86d-cb02"
      }
    ]
  },
  {
    "Id": "options_1771235797800",
    "Name": "Overlord’s Blade",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "ee65-1ae9-d6a8-bd85"
      }
    ]
  },
  {
    "Id": "options_1771235915411",
    "Name": "Lord’s blade",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "3e51-82d1-9725-3333"
      }
    ]
  },
  {
    "Id": "options_1771236002120",
    "Name": "Nanoscarab Amulet",
    "Type": 2,
    "ItemsToAdd": [
      {
        "Id": "rule_222"
      }
    ]
  },
  {
    "Id": "options_1771236109788",
    "Name": "Resurrection Orb",
    "Type": 2,
    "ItemsToAdd": [
      {
        "Id": "rule_226"
      }
    ]
  },
  {
    "Id": "options_1771236504581",
    "Name": "Staff of Light",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "3bb9-cfd3-a1f4-1d39"
      },
      {
        "Id": "7403-f6-6b4-944f"
      }
    ]
  },
  {
    "Id": "options_1771236596818",
    "Name": "Voidscythe",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "6f84-3570-32eb-e1a3"
      }
    ]
  },
  {
    "Id": "options_1771236778186",
    "Name": "Tesla Carbine",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "64ad-95a3-ce2f-ecf2"
      }
    ]
  },
  {
    "Id": "options_1771237015566",
    "Name": "Gauss Reaper",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "6d5d-6878-1274-18cc"
      }
    ]
  },
  {
    "Id": "options_1771237161940",
    "Name": "Tesla Caster",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1770897697685"
      }
    ]
  },
  {
    "Id": "options_1771237249957",
    "Name": "Accelerator Mandible",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rules_1770897244884"
      }
    ]
  },
  {
    "Id": "options_1771237322487",
    "Name": "Nanoscarab Projector",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rules_1770897260599"
      }
    ]
  },
  {
    "Id": "options_1771237444759",
    "Name": "2 Particle Beamers",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "903f-ac42-963b-ffd6"
      }
    ]
  },
  {
    "Id": "options_1771237520788",
    "Name": "Fabricator Claw Array",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_271"
      }
    ]
  },
  {
    "Id": "options_1771237569079",
    "Name": "Gloom Prism",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_320"
      }
    ]
  },
  {
    "Id": "options_1771237623235",
    "Name": "Transdimensional Isolator",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1770899005594"
      }
    ]
  },
  {
    "Id": "options_1771237706128",
    "Name": "Particle Caster",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "7ba3-7c24-b653-d281"
      }
    ]
  },
  {
    "Id": "options_1771237754123",
    "Name": "Transdimensional Beamer",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "58e9-d6a8-2615-fbda"
      }
    ]
  },
  {
    "Id": "options_1771237803526",
    "Name": "Whip Coils",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "db2f-a98e-4d59-6193"
      }
    ]
  },
  {
    "Id": "options_1771237884618",
    "Name": "Enmitic Exterminator.",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "352f-e231-877a-fc51"
      }
    ]
  },
  {
    "Id": "options_1771237968359",
    "Name": "Hyperphase Sword & Dispersion Shield",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "c473-cc38-3b86-f24a"
      },
      {
        "Id": "rule_252"
      }
    ]
  },
  {
    "Id": "options_1771238334779",
    "Name": "4 Death Rays",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "de95-9dd7-c085-26c3"
      }
    ]
  },
  {
    "Id": "options_1771238514697",
    "Name": "Plasmacyte",
    "Type": 7,
    "ExtraItems": [
      {
        "Id": "tokens_1771238685137",
        "Type": "Token"
      }
    ]
  },
  {
    "Id": "options_1771239455921",
    "Name": "Particle Beamer",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "2791-9fe6-3479-547"
      }
    ]
  },
  {
    "Id": "options_1771239516069",
    "Name": "Twin Tesla Carbine",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "551a-9c49-858c-f83d"
      }
    ]
  },
  {
    "Id": "options_1771239587677",
    "Name": "Shieldvanes",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_280"
      }
    ]
  },
  {
    "Id": "options_1771239634982",
    "Name": "Nebuloscope",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_279"
      }
    ]
  },
  {
    "Id": "options_1771239670270",
    "Name": "Shadowloom",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_278"
      }
    ]
  },
  {
    "Id": "options_1771239709352",
    "Name": "Particle Caster & Voidblade.",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "4a54-5368-186c-3e5a"
      },
      {
        "Id": "70cb-2c07-d39d-c741"
      }
    ]
  },
  {
    "Id": "options_1771239830697",
    "Name": "Particle Shredder",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "368a-9e23-69ff-75a7"
      }
    ]
  },
  {
    "Id": "options_1771239887065",
    "Name": "Heavy Gauss Cannon Array",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "231d-94d0-55e7-9098"
      }
    ]
  },
  {
    "Id": "options_1771239946142",
    "Name": "2 Synaptic Obliterators & 2 Transdimensional Projectors",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "d103-220a-14-bebd"
      },
      {
        "Id": "d56a-467d-ecb9-9b6"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/40k/Genestealer Cults/options.json
[
  {
    "Id": "options_1773326608126",
    "Name": "Cult Sniper & Close Combat Weapon.",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "85d6-5734-14b3-2203"
      },
      {
        "Id": "equipment_1773325629745"
      }
    ]
  },
  {
    "Id": "options_1773327156138",
    "Name": "Cult Icon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_3864"
      }
    ]
  },
  {
    "Id": "options_1773327199481",
    "Name": "Heavy Mining Tool",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "174b-b4c0-d61d-dfb9"
      }
    ]
  },
  {
    "Id": "options_1773327263441",
    "Name": "Leader's bio-weapons",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "dc5c-4c49-337b-4281"
      }
    ]
  },
  {
    "Id": "options_1773327657908",
    "Name": "Demolition Charges",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "8429-4679-97cf-4b05"
      }
    ]
  },
  {
    "Id": "options_1773328423089",
    "Name": "Heavy stubber",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "c8a1-9a5-b48e-135f"
      }
    ]
  },
  {
    "Id": "options_1773328451582",
    "Name": "Mining laser",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "5868-96cd-cdcc-2943"
      }
    ]
  },
  {
    "Id": "options_1773328489082",
    "Name": "Seismic cannon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "8e40-1ced-3c41-9851"
      }
    ]
  },
  {
    "Id": "options_1773328543398",
    "Name": "Flamer",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "de59-6c4-4556-6c0e"
      }
    ]
  },
  {
    "Id": "options_1773328573997",
    "Name": "Grenade launcher",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "4a9d-f7f6-4026-5273"
      },
      {
        "Id": "f16-d4b5-befc-8fd7"
      }
    ]
  },
  {
    "Id": "options_1773328600423",
    "Name": "Webber",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "9311-dec4-b9c3-a03"
      }
    ]
  },
  {
    "Id": "options_1773328695135",
    "Name": "Anointed Pistol & Chainsword",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "b6cb-8dfa-d136-2ad4"
      },
      {
        "Id": "a96c-7c07-976b-409a"
      }
    ]
  },
  {
    "Id": "options_1773328764003",
    "Name": "Anointed Pistol & Power Weapon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "b6cb-8dfa-d136-2ad4"
      },
      {
        "Id": "535f-b966-6118-9040"
      }
    ]
  },
  {
    "Id": "options_1773329318249",
    "Name": "Achilles Missile Launcher",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "445c-216b-baa5-214"
      }
    ]
  },
  {
    "Id": "options_1773329356755",
    "Name": "Heavy Mortar",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "ea6f-9f30-3a62-379"
      }
    ]
  },
  {
    "Id": "options_1773329394927",
    "Name": "Spotter",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_3815"
      }
    ]
  },
  {
    "Id": "options_1773329427906",
    "Name": "Survey Augur",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_3816"
      }
    ]
  },
  {
    "Id": "options_1773329829659",
    "Name": "Atalan Power Weapon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "5ab5-695a-fbe9-39e1"
      }
    ]
  },
  {
    "Id": "options_1773329900263",
    "Name": "Atalan Incinerator",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "1aa5-8d88-59da-bac3"
      }
    ]
  },
  {
    "Id": "options_1773329949658",
    "Name": "Mining Laser",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "32fb-3f61-367c-fb71"
      }
    ]
  },
  {
    "Id": "options_1773392317408",
    "Name": "Hand Flamer",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "2674-bc9a-7cbf-6c68"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/40k/Drukhari/options.json
[
  {
    "Id": "options_1771836629078",
    "Name": "Blast Pistol",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "9a52-4491-7eae-8c43"
      }
    ]
  },
  {
    "Id": "options_1771836680348",
    "Name": "Soul Trap",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "rules_1771836061760"
      }
    ]
  },
  {
    "Id": "options_1771836724868",
    "Name": "Agoniser",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "b856-1d1d-8ac1-85ec"
      }
    ]
  },
  {
    "Id": "options_1771836757124",
    "Name": "Master-crafted Power Weapon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1761812692853"
      }
    ]
  },
  {
    "Id": "options_1771843049594",
    "Name": "Power Weapon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1761814582153"
      }
    ]
  },
  {
    "Id": "options_1771843094802",
    "Name": "Kabalite Icon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rules_1771843130599"
      }
    ]
  },
  {
    "Id": "options_1771843172367",
    "Name": "Phantasm Grenade Launcher",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_1846"
      }
    ]
  },
  {
    "Id": "options_1771843272705",
    "Name": "Blast Pistol",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "59c1-f7b9-f86c-6cbb"
      }
    ]
  },
  {
    "Id": "options_1771843356164",
    "Name": "Splinter Pistol",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "71b5-8a93-8a3f-924d"
      }
    ]
  },
  {
    "Id": "options_1771843528552",
    "Name": "Blaster",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "147b-c104-ef93-7111"
      }
    ]
  },
  {
    "Id": "options_1771843572183",
    "Name": "Dark Lance",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "8c0e-9b20-8e64-cd04"
      }
    ]
  },
  {
    "Id": "options_1771843700387",
    "Name": "Shredder",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "7a3e-6720-5c8-1afe"
      }
    ]
  },
  {
    "Id": "options_1771843748888",
    "Name": "Splinter Cannon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "d58-3463-a019-9da3"
      }
    ]
  },
  {
    "Id": "options_1771845104459",
    "Name": "Hexrifle & Torturer’s Tool",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "fe1e-9d52-ac-ad66"
      },
      {
        "Id": "equipment_1761814870144"
      }
    ]
  },
  {
    "Id": "options_1771845168383",
    "Name": "Liquifier Gun & Torturer’s Tool",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "aff0-96bd-a962-9304"
      },
      {
        "Id": "equipment_1761814870144"
      }
    ]
  },
  {
    "Id": "options_1771845219140",
    "Name": "Ossefactor & Torturer’s Tool",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "dfc7-bef0-5c30-9d02"
      },
      {
        "Id": "equipment_1761814870144"
      }
    ]
  },
  {
    "Id": "options_1771845281551",
    "Name": "Stinger Pistol & Torturer’s Tool",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "3fb5-fed9-c125-97a7"
      },
      {
        "Id": "equipment_1761814870144"
      }
    ]
  },
  {
    "Id": "options_1771845330010",
    "Name": "Power Weapon & Torturer’s Tool.",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1771844689732"
      },
      {
        "Id": "equipment_1761814870144"
      }
    ]
  },
  {
    "Id": "options_1771846701913",
    "Name": "Gladiatorial Weapons",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1761815135333"
      }
    ]
  },
  {
    "Id": "options_1771848417969",
    "Name": "Neuro Disruptor",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "1cf4-43f7-4ff2-b8a4"
      }
    ]
  },
  {
    "Id": "options_1771848490979",
    "Name": "Shuriken Rifle",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "2522-d81b-7b47-3b25"
      }
    ]
  },
  {
    "Id": "options_1771848689805",
    "Name": "shuriken cannon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "7eb5-647a-82c8-4309"
      }
    ]
  },
  {
    "Id": "options_1771848739161",
    "Name": "Wraithcannon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "9f0d-2a87-98eb-5cfb"
      }
    ]
  },
  {
    "Id": "options_1771855173950",
    "Name": "Stinger Pistol",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "b039-d693-86fe-4cc7"
      }
    ]
  },
  {
    "Id": "options_1771855227251",
    "Name": "Shardcarbine",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "e2bd-2fa5-4a4b-e552"
      }
    ]
  },
  {
    "Id": "options_1771855257987",
    "Name": "Pain Sculptors",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1761816476334"
      }
    ]
  },
  {
    "Id": "options_1771855306347",
    "Name": "Splinter Pistol & Razorflail",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "71b5-8a93-8a3f-924d"
      },
      {
        "Id": "equipment_1761816572389"
      }
    ]
  },
  {
    "Id": "options_1771855385167",
    "Name": "Stimm-needler",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rules_1771855406456"
      }
    ]
  },
  {
    "Id": "options_1771856218542",
    "Name": "Splinter Pistol & Power Weapon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "71b5-8a93-8a3f-924d"
      },
      {
        "Id": "equipment_1771856001183"
      }
    ]
  },
  {
    "Id": "options_1771856282354",
    "Name": "Splinter Pistol & Stunclaw",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "71b5-8a93-8a3f-924d"
      },
      {
        "Id": "equipment_1761816946844"
      }
    ]
  },
  {
    "Id": "options_1771856380791",
    "Name": "Splinter Pistol & Hellglaive",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "71b5-8a93-8a3f-924d"
      }
    ]
  },
  {
    "Id": "options_1771857057355",
    "Name": "Demiklaives",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "18c6-d3d-2197-925c"
      },
      {
        "Id": "dd06-c3a6-9bd1-13e7"
      }
    ]
  },
  {
    "Id": "options_1771857096668",
    "Name": "Incubi Shrine token",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rules_1771857029136"
      }
    ]
  },
  {
    "Id": "options_1771863279827",
    "Name": "2 Disintegrator Cannons",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "8ac9-bd8f-3c8f-20b2"
      }
    ]
  },
  {
    "Id": "options_1771863320250",
    "Name": "Splinter Cannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "2d92-9836-d7f3-eead"
      }
    ]
  },
  {
    "Id": "options_1771863957503",
    "Name": "Heat Lance",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "944f-56c1-8fdf-417a"
      }
    ]
  },
  {
    "Id": "options_1771864162252",
    "Name": "Cluster Caltrops",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_2016"
      }
    ]
  },
  {
    "Id": "options_1771864201185",
    "Name": "Grav-talon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rules_1771864219159"
      }
    ]
  },
  {
    "Id": "options_1771865266712",
    "Name": "Blast Pistol & Power Weapon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "59c1-f7b9-f86c-6cbb"
      },
      {
        "Id": "equipment_1761814582153"
      }
    ]
  },
  {
    "Id": "options_1771865450620",
    "Name": "Haywire Blaster",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1764673833426"
      }
    ]
  },
  {
    "Id": "options_1771867166682",
    "Name": "Stinger Pod",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "d9a5-dd35-4192-d5b"
      }
    ]
  },
  {
    "Id": "options_1771867212220",
    "Name": "Twin Haywire Blaster",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "3024-e635-ec49-a675"
      }
    ]
  },
  {
    "Id": "options_1771867246456",
    "Name": "Twin Heat Lance",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1771866577505"
      }
    ]
  },
  {
    "Id": "options_1771867284138",
    "Name": "Talos Ichor Injector",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "675a-591f-9994-3e6d"
      }
    ]
  },
  {
    "Id": "options_1771867318461",
    "Name": "Twin Liquifier Gun",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "ffc0-37b8-452a-d83d"
      }
    ]
  },
  {
    "Id": "options_1771867352207",
    "Name": "Chain Flails",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "d94a-9048-69f0-fd75"
      }
    ]
  },
  {
    "Id": "options_1771867396705",
    "Name": "Talos gauntlet",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "ad2d-d40c-6967-edcd"
      }
    ]
  },
  {
    "Id": "options_1771867906061",
    "Name": "2 Dark Scythes",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1771867613101"
      }
    ]
  }
]
