=== Jucyliana/WDS2.0/schemas/options.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Options Schema",
  "description": "Schema for options.json files containing unit/model customization options",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Id", "Name", "Type"],
    "properties": {
      "Id": {
        "type": "string",
        "description": "Unique identifier for the option"
      },
      "Name": {
        "type": "string",
        "description": "Name of the option"
      },
      "Type": {
        "type": "integer",
        "minimum": 0,
        "maximum": 7,
        "description": "Type of option - determines how it affects units/models (0=SwapUnit, 1=ModifyItemOnAll, 2=ModifyItemOnBasic, 3=SwapBasic, 4=ModifyItemOnSingle, 5=SwapSingle, 6=AddSingle, 7=AddExtras)"
      },
      "ItemsToAdd": {
        "type": "array",
        "description": "Array of items to add (statlines, rules, equipment, etc.)",
        "items": {
          "type": "object",
          "required": ["Id"],
          "properties": {
            "Id": {
              "type": "string",
              "description": "ID of the item to add"
            },
            "Info": {
              "type": "string",
              "description": "Optional additional information about the item"
            }
          },
          "additionalProperties": false
        }
      },
      "ExtraItems": {
        "type": "array",
        "description": "List of extra items (cards, units, etc.) associated with this option",
        "items": {
          "type": "object",
          "required": ["Id", "Type"],
          "properties": {
            "Id": {
              "type": "string",
              "description": "ID of the extra item. Just deployable items like cards, tokens, cardstacks or units for now, but could be extended to other types if needed"
            },
            "Type": {
              "type": "string",
              "enum": ["Unit", "Card", "Token", "Cardstack", "Rule", "Equipment", "Statline"],
              "description": "Type of the extra item"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  }
}

=== Jucyliana/WDS2.0/40k/World Eaters/options.json
[
  {
    "Id": "options_1774968674639",
    "Name": "Ectoplasma destructor",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1774968035989"
      }
    ]
  },
  {
    "Id": "options_1774968698356",
    "Name": "Magma cutters",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1774968151566"
      }
    ]
  },
  {
    "Id": "options_1774968724514",
    "Name": "Hades lascannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1774968265509"
      }
    ]
  },
  {
    "Id": "options_1774968803866",
    "Name": "Heavy reaper autocannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1774968314677"
      }
    ]
  },
  {
    "Id": "options_1774968848614",
    "Name": "Electroscourge",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1774968598262"
      }
    ]
  },
  {
    "Id": "options_1775735277154",
    "Name": "Axe of Khorne & Bloodflail",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "6260-10af-22ef-f664"
      },
      {
        "Id": "a72c-25d4-1924-fe3c"
      },
      {
        "Id": "6fe5-b0db-58e3-ab95"
      }
    ]
  },
  {
    "Id": "options_1775735331334",
    "Name": "Axe of Khorne & Lash of Khorne",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "6260-10af-22ef-f664"
      },
      {
        "Id": "a72c-25d4-1924-fe3c"
      },
      {
        "Id": "a6a3-e0e6-f400-ac07"
      }
    ]
  },
  {
    "Id": "options_1777368752119",
    "Name": "Instrument of Chaos",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_625"
      }
    ]
  },
  {
    "Id": "options_1777368785962",
    "Name": "Daemonic icon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_624"
      }
    ]
  },
  {
    "Id": "options_1777369509368",
    "Name": "Plasma Pistol",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "equipment_1777369223316"
      },
      {
        "Id": "equipment_1777369196864"
      }
    ]
  },
  {
    "Id": "options_1777369576406",
    "Name": "Khornate Eviscerator",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "1438-6f84-786f-794d"
      }
    ]
  },
  {
    "Id": "options_1777369605738",
    "Name": "Icon of Khorne",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "rule_1311"
      }
    ]
  },
  {
    "Id": "options_1777369863193",
    "Name": "Combi-weapon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "5397-9c3d-25dc-9f25"
      }
    ]
  },
  {
    "Id": "options_1777369985876",
    "Name": "Havoc launcher",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "0bbc-60b7-e869-01a8"
      }
    ]
  },
  {
    "Id": "options_1777371633224",
    "Name": "Combi-bolter",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "8055-8f34-66e4-dc87"
      }
    ]
  },
  {
    "Id": "options_1777371819860",
    "Name": "2 heavy bolters",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "55cd-6458-4bb4-8c5c"
      }
    ]
  },
  {
    "Id": "options_1777371853966",
    "Name": "2 lascannons",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "1b09-07ca-bfa2-b30f"
      }
    ]
  },
  {
    "Id": "options_1777372841973",
    "Name": "Heavy flamer",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "ab67-d80a-c94c-e6e3"
      }
    ]
  },
  {
    "Id": "options_1777372881382",
    "Name": "Reaper Autocannon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "2db4-7c20-3e1d-77ff"
      }
    ]
  },
  {
    "Id": "options_1777372937144",
    "Name": "Combi-weapon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "5397-9c3d-25dc-9f25"
      }
    ]
  },
  {
    "Id": "options_1777372978538",
    "Name": "Paired Accursed Weapons",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "d4df-8ce0-767a-474d"
      }
    ]
  },
  {
    "Id": "options_1777373011341",
    "Name": "Power Fist",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "93fd-b43b-37d3-e3a3"
      }
    ]
  },
  {
    "Id": "options_1777373093339",
    "Name": "Chainfist",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "6044-c4f2-8321-fd60"
      }
    ]
  },
  {
    "Id": "options_1777374951025",
    "Name": "2 Ectoplasma Cannons",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "f2ce-191d-8203-cfcd"
      }
    ]
  },
  {
    "Id": "options_1777375012924",
    "Name": "Ectoplasma cannon & Forgefiend claws",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "f2ce-191d-8203-cfcd"
      },
      {
        "Id": "ed63-295b-eaeb-eae2"
      }
    ]
  },
  {
    "Id": "options_1777375577357",
    "Name": "Autopistol",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "3662-4f69-8bee-ee9f"
      }
    ]
  },
  {
    "Id": "options_1777375611492",
    "Name": "Blood Harpoon",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "2ab9-9476-357e-da20"
      }
    ]
  },
  {
    "Id": "options_1777376776652",
    "Name": "Plasma cannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "55df-3e4e-7496-90c5"
      }
    ]
  },
  {
    "Id": "options_1777376810338",
    "Name": "Twin autocannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "d49f-822-633e-12e"
      }
    ]
  },
  {
    "Id": "options_1777376869550",
    "Name": "Twin heavy bolter",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "fc72-9f62-b714-d195"
      }
    ]
  },
  {
    "Id": "options_1777376905477",
    "Name": "Twin lascannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "9eb6-d9a7-c754-c1a6"
      }
    ]
  },
  {
    "Id": "options_1777376947268",
    "Name": "Helbrute fist",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "9cf0-22da-7500-4848"
      }
    ]
  },
  {
    "Id": "options_1777376988461",
    "Name": "Helbrute hammer",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "fc6f-24af-e553-0c3d"
      }
    ]
  },
  {
    "Id": "options_1777377012516",
    "Name": "Power scourge",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "b7a2-e159-fe07-db5d"
      }
    ]
  },
  {
    "Id": "options_1777377048978",
    "Name": "Heavy flamer",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "ab67-d80a-c94c-e6e3"
      }
    ]
  },
  {
    "Id": "options_1777377398538",
    "Name": "Baleflamer",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "a649-2296-8c56-08cd"
      }
    ]
  },
  {
    "Id": "options_1777377688756",
    "Name": "Mauler chainblade",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "c75c-6f52-8160-7262"
      }
    ]
  },
  {
    "Id": "options_1777377714710",
    "Name": "Skullsmasher and Mangler",
    "Type": 4,
    "ItemsToAdd": [
      {
        "Id": "ab0e-4569-3ddc-3e81"
      }
    ]
  },
  {
    "Id": "options_1777377942860",
    "Name": "Daemongore cannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "046f-8be9-131b-0ed8"
      }
    ]
  },
  {
    "Id": "options_1777377972844",
    "Name": "Ichor cannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "624a-be29-77f2-203b"
      }
    ]
  },
  {
    "Id": "options_1777378004517",
    "Name": "Skullhurler",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "1f29-6965-2404-190c"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/40k/Imperial Knights/options.json
[
  {
    "Id": "options_1775472743397",
    "Name": "Bellatus reaper chainsword",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1775465700403"
      },
      {
        "Id": "equipment_1775465716179"
      }
    ]
  },
  {
    "Id": "options_1775472794571",
    "Name": "Thundershock spear",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1775472034002"
      },
      {
        "Id": "equipment_1775472088912"
      }
    ]
  },
  {
    "Id": "options_1775634549467",
    "Name": "Questoris heavy stubber",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "19b5-e47a-9e29-d6db"
      }
    ]
  },
  {
    "Id": "options_1775634611685",
    "Name": "Rapid-fire battle cannon & Questoris heavy stubber",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "e63e-93fd-e131-fe85"
      },
      {
        "Id": "19b5-e47a-9e29-d6db"
      }
    ]
  },
  {
    "Id": "options_1775634672761",
    "Name": "Ironstorm missile pod",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "712a-105f-a24e-badb"
      }
    ]
  },
  {
    "Id": "options_1775634701799",
    "Name": "Stormspear rocket pod",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "4dbb-a82d-89ff-e62e"
      }
    ]
  },
  {
    "Id": "options_1775634736314",
    "Name": "Twin Icarus autocannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1762431766337"
      }
    ]
  },
  {
    "Id": "options_1775637125832",
    "Name": "Thunderstrike gauntlet",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "d2f7-1f2a-e319-9e6a"
      },
      {
        "Id": "dc7b-57c8-2678-6b40"
      }
    ]
  },
  {
    "Id": "options_1775639441628",
    "Name": "Meltagun",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "4b6f-2df5-d7b6-34dd"
      }
    ]
  },
  {
    "Id": "options_1775643294113",
    "Name": "Hekaton siege claw & Twin rad cleanser",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "equipment_1762510001131"
      },
      {
        "Id": "equipment_1762510128819"
      },
      {
        "Id": "3a9f-c444-b1d4-c31c"
      }
    ]
  },
  {
    "Id": "options_1775644707212",
    "Name": "helios defence missiles",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "ee88-6de7-ede9-c612"
      }
    ]
  },
  {
    "Id": "options_1775644716057",
    "Name": "2 Lascannons",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "1898-d8d0-7e42-652d"
      }
    ]
  },
  {
    "Id": "options_1775644799757",
    "Name": "Acastus autocannon & Lascannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "1898-d8d0-7e42-652d"
      }
    ]
  },
  {
    "Id": "options_1775645083898",
    "Name": "Siege claw & Rad cleanser",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "165d-95f5-f19e-8016"
      },
      {
        "Id": "ec3a-304-38d3-eb09"
      }
    ]
  },
  {
    "Id": "options_1775645301053",
    "Name": "Lightning lock",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "b9d1-1e57-836-a531"
      }
    ]
  },
  {
    "Id": "options_1775645391830",
    "Name": "Conversion beam cannon",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "fec2-9b94-3ebd-f1a4"
      }
    ]
  },
  {
    "Id": "options_1775645443122",
    "Name": "Graviton pulsar",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "9401-8675-2bac-35b"
      }
    ]
  },
  {
    "Id": "options_1775645466972",
    "Name": "Volkite veuglaire",
    "Type": 1,
    "ItemsToAdd": [
      {
        "Id": "b5d6-3736-74ec-1e93"
      }
    ]
  }
]
