=== Jucyliana/WDS2.0/schemas/statlines.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Statlines Schema",
  "description": "Schema for statlines.json files containing game attribute statlines",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Id", "Name", "Type"],
    "properties": {
      "Id": {
        "type": "string",
        "description": "Unique identifier for the statline"
      },
      "Name": {
        "type": "string",
        "description": "Name of the statline"
      },
      "Type": {
        "type": "string",
        "enum": ["Statline"],
        "description": "Type indicator for statline entries"
      },
      "Attributes": {
        "type": "object",
        "description": "Object containing game attributes (M, T, SV, W, LD, OC, IS, etc.)",
        "additionalProperties": {
          "type": ["string", "null"]
        }
      },
      "Children": {
        "type": "array",
        "description": "Array of child items (statlines, rules, equipment, etc.)",
        "items": {
          "type": "object",
          "required": ["Id"],
          "properties": {
            "Id": {
              "type": "string",
              "description": "ID of the child item"
            },
            "Info": {
              "type": "string",
              "description": "Optional additional information about the item"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  }
}

=== Jucyliana/WDS2.0/TOW/High Elf Realms - Sea Guard Garrison/statlines.json
[
  {
    "Id": "statline_378",
    "Name": "Sea Guard Garrison Commander",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "6",
      "BS": "7",
      "S": "4",
      "T": "3",
      "W": "2",
      "I": "5",
      "A": "3",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "d6b8-1ad9-d024-1d72"
      }
    ]
  },
  {
    "Id": "statline_379",
    "Name": "Ship's Company",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "d6b8-1ad9-d024-1d72"
      }
    ]
  },
  {
    "Id": "statline_380",
    "Name": "Midshipman",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "5",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "d6b8-1ad9-d024-1d72"
      }
    ]
  },
  {
    "Id": "statline_381",
    "Name": "Bosun",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "2",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "d6b8-1ad9-d024-1d72"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/Tomb Kings of Khemri/statlines.json
[
  {
    "Id": "statline_668",
    "Name": "Winged Warsphinx",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "4",
      "BS": "0",
      "S": "5",
      "T": "6",
      "W": "5",
      "I": "1",
      "A": "4",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "8382-4e23-e72c-d90"
      },
      {
        "Id": "3845-49d0-ec6f-589"
      },
      {
        "Id": "2c1-76db-c762-d51e"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/40k/Iron Hands/statlines.json
[
  {
    "Id": "statline_2566",
    "Name": "Iron Father Feirros",
    "Type": "Statline",
    "Attributes": {
      "M": "5\"",
      "T": "6",
      "SV": "2+",
      "W": "6",
      "LD": "6+",
      "OC": "1"
    }
  },
  {
    "Id": "statline_2567",
    "Name": "Caanok Var",
    "Type": "Statline",
    "Attributes": {
      "M": "5\"",
      "T": "5",
      "SV": "2+",
      "W": "6",
      "LD": "6+",
      "OC": "1"
    }
  },
  {
    "Id": "statline_2568",
    "Name": "Gorgon's Wrath",
    "Type": "Statline",
    "Attributes": {
      "Range": "36\"",
      "A": "3",
      "BS": "2+",
      "S": "5",
      "AP": "-1",
      "D": "2"
    }
  },
  {
    "Id": "statline_2569",
    "Name": "Harrowhand",
    "Type": "Statline",
    "Attributes": {
      "Range": "Melee",
      "A": "6",
      "WS": "3+",
      "S": "7",
      "AP": "-2",
      "D": "2"
    }
  },
  {
    "Id": "statline_2570",
    "Name": "Medusan Manipuli",
    "Type": "Statline",
    "Attributes": {
      "Range": "Melee",
      "A": "2",
      "WS": "3+",
      "S": "8",
      "AP": "-2",
      "D": "3"
    }
  },
  {
    "Id": "statline_2571",
    "Name": "Axiom - Strike",
    "Type": "Statline",
    "Attributes": {
      "Range": "Melee",
      "A": "5",
      "WS": "2+",
      "S": "8",
      "AP": "-2",
      "D": "2"
    }
  },
  {
    "Id": "statline_2572",
    "Name": "Axiom - Sweep",
    "Type": "Statline",
    "Attributes": {
      "Range": "Melee",
      "A": "10",
      "WS": "2+",
      "S": "5",
      "AP": "-2",
      "D": "1"
    }
  },
  {
    "Id": "statlines_1777536414032",
    "Name": "Storm bolter",
    "Type": "Statline",
    "Attributes": {
      "Range": "24\"",
      "A": "2",
      "BS": "2+",
      "S": "4",
      "AP": "0",
      "D": "1"
    }
  },
  {
    "Id": "statlines_1777536527561",
    "Name": "Bolt pistol",
    "Type": "Statline",
    "Attributes": {
      "Range": "12\"",
      "A": "1",
      "BS": "2+",
      "S": "4",
      "AP": "0",
      "D": "1"
    }
  }
]

=== Jucyliana/WDS2.0/TOW/Wood Elf Realms/statlines.json
[
  {
    "Id": "statline_864",
    "Name": "Deepwood Hound",
    "Type": "Statline",
    "Attributes": {
      "M": "9",
      "WS": "4",
      "BS": "-",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "5"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/WAP/Estalia/statlines.json
[
  {
    "Id": "statline_515",
    "Name": "Eminent Magus",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "3",
      "I": "3",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_516",
    "Name": "Grand Commander",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "6",
      "BS": "5",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "6",
      "A": "4",
      "LD": "9"
    }
  },
  {
    "Id": "statline_517",
    "Name": "Auroch",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "3",
      "BS": null,
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "3",
      "A": "3",
      "LD": "6"
    }
  },
  {
    "Id": "statline_518",
    "Name": "High Inquisitor",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "4",
      "A": "2",
      "LD": "9"
    }
  },
  {
    "Id": "statline_519",
    "Name": "Santiago de Vivar",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "7",
      "BS": "5",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "6",
      "A": "5",
      "LD": "9"
    }
  },
  {
    "Id": "statline_520",
    "Name": "Babieca",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "3",
      "BS": "",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_521",
    "Name": "Diestro",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "6",
      "BS": "5",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "6",
      "A": "3",
      "LD": "8"
    }
  },
  {
    "Id": "statline_522",
    "Name": "Inquisitor",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "4",
      "A": "2",
      "LD": "8"
    }
  },
  {
    "Id": "statline_523",
    "Name": "Battle Magus",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "2",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_524",
    "Name": "Priestess of Myrmidia",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "4",
      "A": "2",
      "LD": "8"
    }
  },
  {
    "Id": "statline_525",
    "Name": "Altar",
    "Type": "Statline",
    "Attributes": {
      "M": null,
      "WS": null,
      "BS": null,
      "S": null,
      "T": "5",
      "W": "5",
      "I": null,
      "A": null,
      "LD": null
    }
  },
  {
    "Id": "statline_526",
    "Name": "Maria de Salvo",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "7",
      "BS": "5",
      "S": "4",
      "T": "3",
      "W": "2",
      "I": "7",
      "A": "3",
      "LD": "9"
    }
  },
  {
    "Id": "statline_527",
    "Name": "Almogavar",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_528",
    "Name": "Arquebusier",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_529",
    "Name": "Caballero",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_530",
    "Name": "Conquistador",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_531",
    "Name": "Genitor",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_532",
    "Name": "Marine",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_533",
    "Name": "Rodelero",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_534",
    "Name": "Tercio",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_535",
    "Name": "War Dog",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "3",
      "BS": "",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_536",
    "Name": "Falconet",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "",
      "BS": "",
      "S": "",
      "T": "7",
      "W": "",
      "I": "",
      "A": "",
      "LD": ""
    }
  },
  {
    "Id": "statline_537",
    "Name": "Grenadier",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_538",
    "Name": "Mountain Bandit",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_539",
    "Name": "Royal Guard",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_540",
    "Name": "Sister of Fury",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_541",
    "Name": "Watchman",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_542",
    "Name": "Culverin",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "",
      "BS": "",
      "S": "",
      "T": "7",
      "W": "",
      "I": "",
      "A": "",
      "LD": ""
    }
  },
  {
    "Id": "statline_543",
    "Name": "Fire Bull",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "3",
      "BS": "",
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_544",
    "Name": "Knight of the Raging Bull",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_545",
    "Name": "Auroch",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "3",
      "BS": "",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "3",
      "A": "3",
      "LD": "6"
    }
  },
  {
    "Id": "statline_546",
    "Name": "Lombard",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "",
      "BS": "",
      "S": "",
      "T": "7",
      "W": "",
      "I": "",
      "A": "",
      "LD": ""
    }
  }
]

=== Jucyliana/WDS2.0/WAP/Halflings/statlines.json
[
  {
    "Id": "statline_610",
    "Name": "Moot Elder",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "6",
      "S": "3",
      "T": "3",
      "W": "3",
      "I": "7",
      "A": "4",
      "LD": "10"
    }
  },
  {
    "Id": "statline_611",
    "Name": "Farm Animal",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "2",
      "BS": null,
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "3"
    }
  },
  {
    "Id": "statline_612",
    "Name": "Giant Swan",
    "Type": "Statline",
    "Attributes": {
      "M": "2",
      "WS": "3",
      "BS": null,
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_613",
    "Name": "Ogre Bodyguard",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": null,
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "2",
      "A": "4",
      "LD": "7"
    }
  },
  {
    "Id": "statline_614",
    "Name": "Nicholas Warfoot",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "6",
      "BS": "7",
      "S": "3",
      "T": "3",
      "W": "3",
      "I": "7",
      "A": "4",
      "LD": "10"
    }
  },
  {
    "Id": "statline_615",
    "Name": "Herbalist",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "2",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_616",
    "Name": "Master Chef",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "2",
      "I": "6",
      "A": "2",
      "LD": "9"
    }
  },
  {
    "Id": "statline_617",
    "Name": "Chuck Wagon",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": null,
      "BS": null,
      "S": "4",
      "T": "4",
      "W": "3",
      "I": null,
      "A": null,
      "LD": null
    }
  },
  {
    "Id": "statline_618",
    "Name": "Cook",
    "Type": "Statline",
    "Attributes": {
      "M": null,
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": null,
      "W": null,
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_619",
    "Name": "Master Thief",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "6",
      "S": "3",
      "T": "3",
      "W": "2",
      "I": "8",
      "A": "3",
      "LD": "9"
    }
  },
  {
    "Id": "statline_620",
    "Name": "Sheriff",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "6",
      "S": "3",
      "T": "3",
      "W": "2",
      "I": "7",
      "A": "3",
      "LD": "9"
    }
  },
  {
    "Id": "statline_621",
    "Name": "Ogglethorpe Bulnhelm",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "2",
      "I": "6",
      "A": "2",
      "LD": "9"
    }
  },
  {
    "Id": "statline_622",
    "Name": "Fieldwarden",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_623",
    "Name": "Hobilar",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_624",
    "Name": "Farm Animal",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "2",
      "BS": "",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "3"
    }
  },
  {
    "Id": "statline_625",
    "Name": "Archer",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_626",
    "Name": "Spearman",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_627",
    "Name": "Swordsman",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_628",
    "Name": "Beekeeper",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_629",
    "Name": "Deputy",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_630",
    "Name": "Gamekeeper",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "5",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_631",
    "Name": "Housewife",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "3",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_632",
    "Name": "Reaper",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "",
      "BS": "",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "",
      "A": "",
      "LD": ""
    }
  },
  {
    "Id": "statline_633",
    "Name": "Farmer",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "",
      "W": "",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_634",
    "Name": "Swan Rider",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "6",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_635",
    "Name": "Giant Swan",
    "Type": "Statline",
    "Attributes": {
      "M": "2",
      "WS": "3",
      "BS": "",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_636",
    "Name": "Thief",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "3",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "6",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_637",
    "Name": "Half Tank",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "",
      "BS": "",
      "S": "5",
      "T": "6",
      "W": "6",
      "I": "",
      "A": "",
      "LD": ""
    }
  },
  {
    "Id": "statline_638",
    "Name": "Crew",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "4",
      "S": "2",
      "T": "2",
      "W": "1",
      "I": "5",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_639",
    "Name": "Fireworks Cart",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "",
      "BS": "",
      "S": "",
      "T": "5",
      "W": "",
      "I": "",
      "A": "",
      "LD": ""
    }
  },
  {
    "Id": "statline_640",
    "Name": "Treeman",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "2",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "2",
      "A": "3",
      "LD": "7"
    }
  },
  {
    "Id": "statline_641",
    "Name": "Shearer",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "",
      "BS": "",
      "S": "5",
      "T": "5",
      "W": "4",
      "I": "",
      "A": "",
      "LD": ""
    }
  }
]
