=== Jucyliana/WDS2.0/schemas/statlines.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Statlines Schema",
  "description": "Schema for statlines.json files containing game attribute statlines",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Id", "Name", "Type"],
    "properties": {
      "Id": {
        "type": "string",
        "description": "Unique identifier for the statline"
      },
      "Name": {
        "type": "string",
        "description": "Name of the statline"
      },
      "Type": {
        "type": "string",
        "enum": ["Statline"],
        "description": "Type indicator for statline entries"
      },
      "Attributes": {
        "type": "object",
        "description": "Object containing game attributes (M, T, SV, W, LD, OC, IS, etc.)",
        "additionalProperties": {
          "type": ["string", "null"]
        }
      },
      "Children": {
        "type": "array",
        "description": "Array of child items (statlines, rules, equipment, etc.)",
        "items": {
          "type": "object",
          "required": ["Id"],
          "properties": {
            "Id": {
              "type": "string",
              "description": "ID of the child item"
            },
            "Info": {
              "type": "string",
              "description": "Optional additional information about the item"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  }
}

=== Jucyliana/WDS2.0/WAP/Albion/statlines.json
[
  {
    "Id": "statline_1",
    "Name": "Truthsayer",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "4",
      "A": "2",
      "LD": "9"
    },
    "Children": [
      {
        "Id": "rule_1751004873288"
      }
    ]
  },
  {
    "Id": "statline_2",
    "Name": "Warhorse",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "3",
      "BS": null,
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_3",
    "Name": "Chariot",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": null,
      "BS": null,
      "S": "4",
      "T": "4",
      "W": "3",
      "I": null,
      "A": null,
      "LD": null
    }
  },
  {
    "Id": "statline_4",
    "Name": "Charioteer",
    "Type": "Statline",
    "Attributes": {
      "M": null,
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": null,
      "W": null,
      "I": "3",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_5",
    "Name": "Elk",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "3",
      "BS": "0",
      "S": "4",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_6",
    "Name": "Warleader",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "6",
      "BS": "5",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "6",
      "A": "4",
      "LD": "9"
    },
    "Children": [
      {
        "Id": "rule_1751004873288"
      }
    ]
  },
  {
    "Id": "statline_7",
    "Name": "Mastodon",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": null,
      "S": "5",
      "T": "6",
      "W": "6",
      "I": "1",
      "A": "4",
      "LD": "6"
    }
  },
  {
    "Id": "statline_8",
    "Name": "Crewman",
    "Type": "Statline",
    "Attributes": {
      "M": null,
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": null,
      "W": null,
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_9",
    "Name": "Shieldbearers",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": null,
      "W": null,
      "I": "4",
      "A": "2",
      "LD": null
    }
  },
  {
    "Id": "statline_10",
    "Name": "Chieftain",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "5",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "5",
      "A": "3",
      "LD": "8"
    }
  },
  {
    "Id": "statline_11",
    "Name": "Wyrd Druid",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "3",
      "W": "2",
      "I": "4",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_12",
    "Name": "Aonbarr",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_13",
    "Name": "Warhorse",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "3",
      "BS": "",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_14",
    "Name": "Chariot",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "",
      "BS": "",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "",
      "A": "",
      "LD": ""
    }
  },
  {
    "Id": "statline_15",
    "Name": "Charioteer",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "",
      "W": "",
      "I": "3",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_16",
    "Name": "Chariot Master",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "",
      "W": "",
      "I": "3",
      "A": "2",
      "LD": "8"
    }
  },
  {
    "Id": "statline_17",
    "Name": "Tribal Warrior",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_18",
    "Name": "Hunting Dog",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "3",
      "BS": "",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_19",
    "Name": "Woad Raider",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_20",
    "Name": "Youngbloods",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "6"
    }
  },
  {
    "Id": "statline_21",
    "Name": "Centaur",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "4",
      "A": "2",
      "LD": "8"
    }
  },
  {
    "Id": "statline_22",
    "Name": "Druid Neophyte",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_23",
    "Name": "Fenbeast",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "3",
      "BS": "",
      "S": "5",
      "T": "5",
      "W": "4",
      "I": "1",
      "A": "3",
      "LD": "8"
    }
  },
  {
    "Id": "statline_24",
    "Name": "Half Giant",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "2",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "2",
      "A": "3",
      "LD": "7"
    }
  },
  {
    "Id": "statline_25",
    "Name": "Hearthguard",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_26",
    "Name": "Hunter",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_27",
    "Name": "Pixie Swarm",
    "Type": "Statline",
    "Attributes": {
      "M": "1",
      "WS": "3",
      "BS": "3",
      "S": "1",
      "T": "1",
      "W": "8",
      "I": "5",
      "A": "10",
      "LD": "8"
    }
  },
  {
    "Id": "statline_28",
    "Name": "Swordmaiden",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "8"
    }
  },
  {
    "Id": "statline_29",
    "Name": "Viridian Lord",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "4",
      "A": "2",
      "LD": "9"
    }
  },
  {
    "Id": "statline_30",
    "Name": "Warrior of Danu",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "5",
      "T": "4",
      "W": "2",
      "I": "4",
      "A": "2",
      "LD": "8"
    }
  },
  {
    "Id": "statline_31",
    "Name": "Bonegrinder Giant",
    "Type": "Statline",
    "Attributes": {
      "M": "10",
      "WS": "3",
      "BS": "3",
      "S": "8",
      "T": "8",
      "W": "8",
      "I": "1",
      "A": "",
      "LD": "10"
    }
  },
  {
    "Id": "statline_32",
    "Name": "Fenhulk",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "3",
      "BS": "",
      "S": "6",
      "T": "6",
      "W": "6",
      "I": "1",
      "A": "5",
      "LD": "8"
    }
  },
  {
    "Id": "statline_33",
    "Name": "Giant",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "3",
      "S": "6",
      "T": "6",
      "W": "6",
      "I": "3",
      "A": "",
      "LD": "10"
    }
  },
  {
    "Id": "statline_34",
    "Name": "Mastodon",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "",
      "S": "5",
      "T": "6",
      "W": "6",
      "I": "1",
      "A": "4",
      "LD": "6"
    }
  },
  {
    "Id": "statline_35",
    "Name": "Crewman",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "",
      "W": "",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  },
  {
    "Id": "statline_36",
    "Name": "Stone Thrower",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "",
      "BS": "",
      "S": "",
      "T": "7",
      "W": "",
      "I": "",
      "A": "",
      "LD": ""
    }
  },
  {
    "Id": "statline_37",
    "Name": "Crewman",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "LD": "7"
    }
  }
]

=== Jucyliana/WDS2.0/40k/Salamanders/statlines.json
[
  {
    "Id": "statline_3107",
    "Name": "Adrax Agatone",
    "Type": "Statline",
    "Attributes": {
      "M": "6\"",
      "T": "4",
      "SV": "2+",
      "W": "5",
      "LD": "6+",
      "OC": "1"
    }
  },
  {
    "Id": "statline_3108",
    "Name": "Vulkan He'stan",
    "Type": "Statline",
    "Attributes": {
      "M": "6\"",
      "T": "4",
      "SV": "2+",
      "W": "5",
      "LD": "6+",
      "OC": "1"
    }
  },
  {
    "Id": "statline_3109",
    "Name": "Drakkis",
    "Type": "Statline",
    "Attributes": {
      "Range": "12\"",
      "A": "D6+3",
      "BS": "N/A",
      "S": "4",
      "AP": "-1",
      "D": "1"
    }
  },
  {
    "Id": "statline_3110",
    "Name": "Malleus Noctum",
    "Type": "Statline",
    "Attributes": {
      "Range": "Melee",
      "A": "5",
      "WS": "2+",
      "S": "10",
      "AP": "-2",
      "D": "3"
    }
  },
  {
    "Id": "statline_3111",
    "Name": "Gauntlet of the Forge",
    "Type": "Statline",
    "Attributes": {
      "Range": "12\"",
      "A": "D6+3",
      "BS": "N/A",
      "S": "6",
      "AP": "-1",
      "D": "1"
    }
  },
  {
    "Id": "statline_3112",
    "Name": "Spear of Vulkan",
    "Type": "Statline",
    "Attributes": {
      "Range": "Melee",
      "A": "6",
      "WS": "2+",
      "S": "6",
      "AP": "-2",
      "D": "2"
    }
  },
  {
    "Id": "statlines_1777534675734",
    "Name": "Bolt pistol",
    "Type": "Statline",
    "Attributes": {
      "Range": "12\"",
      "A": "1",
      "BS": "2+",
      "S": "4",
      "AP": "0",
      "D": "1"
    }
  }
]

=== Jucyliana/WDS2.0/TOW/Warriors of Chaos - Wolves of the Sea/statlines.json
[
  {
    "Id": "statline_816",
    "Name": "Marauder Tribe Chieftain",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "4",
      "A": "3",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_817",
    "Name": "Marauder Tribe Berserker",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_818",
    "Name": "Headtaker",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": ""
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      }
    ]
  },
  {
    "Id": "statline_819",
    "Name": "Marauder Tribe Huscarl",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "ee75-c1a8-2f0c-c264"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_820",
    "Name": "First Sword",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "ee75-c1a8-2f0c-c264"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      }
    ]
  },
  {
    "Id": "statline_821",
    "Name": "Skin Wolf",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "5",
      "BS": "-",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "4",
      "A": "3",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_822",
    "Name": "Skin Wolf Jarl",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "5",
      "BS": "-",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "4",
      "A": "4",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/Dwarfen Mountain Holds/statlines.json
[
  {
    "Id": "statline_260",
    "Name": "Dragon Company trooper",
    "Type": "Statline",
    "Attributes": {
      "M": "3",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "2",
      "A": "1",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "3f0e-1dc6-b425-bf59"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "8997-c74d-3a8d-ecf9"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/Dwarfen Mountain Holds - Royal Clan/statlines.json
[
  {
    "Id": "statline_265",
    "Name": "Royal Clan Warrior",
    "Type": "Statline",
    "Attributes": {
      "M": "3",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "2",
      "A": "1",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_266",
    "Name": "Royal Clan Veteran",
    "Type": "Statline",
    "Attributes": {
      "M": "3",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "2",
      "A": "2",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/WAP/Lizardmen/statlines.json
[
  {
    "Id": "statline_774",
    "Name": "Saurus Oldblood",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "6",
      "BS": "",
      "S": "5",
      "T": "5",
      "W": "3",
      "I": "3",
      "A": "5",
      "LD": "8"
    }
  },
  {
    "Id": "statline_775",
    "Name": "Horned One",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "3",
      "BS": null,
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "2",
      "LD": "3"
    }
  },
  {
    "Id": "statline_776",
    "Name": "Carnosaur",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "4",
      "BS": null,
      "S": "6",
      "T": "5",
      "W": "5",
      "I": "2",
      "A": "4",
      "LD": "5"
    }
  },
  {
    "Id": "statline_777",
    "Name": "Slann Mage-Priest",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "1",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "5",
      "I": "1",
      "A": "",
      "LD": "9"
    }
  },
  {
    "Id": "statline_778",
    "Name": "Skink Attendant",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "2",
      "BS": "3",
      "S": "3",
      "T": "",
      "W": "",
      "I": "4",
      "A": "1",
      "LD": ""
    }
  },
  {
    "Id": "statline_779",
    "Name": "Saurus Scar-Veteran",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "",
      "S": "5",
      "T": "5",
      "W": "2",
      "I": "3",
      "A": "4",
      "LD": "8"
    }
  },
  {
    "Id": "statline_780",
    "Name": "Skink Chief",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "4",
      "BS": "5",
      "S": "4",
      "T": "3",
      "W": "2",
      "I": "6",
      "A": "3",
      "LD": "6"
    }
  },
  {
    "Id": "statline_781",
    "Name": "Troglodon",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "3",
      "BS": "4",
      "S": "5",
      "T": "5",
      "W": "5",
      "I": "2",
      "A": "3",
      "LD": "5"
    }
  },
  {
    "Id": "statline_782",
    "Name": "Ripperdactyl",
    "Type": "Statline",
    "Attributes": {
      "M": "2",
      "WS": "3",
      "BS": null,
      "S": "4",
      "T": "3",
      "W": "2",
      "I": "3",
      "A": "2",
      "LD": "3"
    }
  },
  {
    "Id": "statline_783",
    "Name": "Stegadon",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": null,
      "S": "5",
      "T": "6",
      "W": "5",
      "I": "2",
      "A": "4",
      "LD": "6"
    }
  },
  {
    "Id": "statline_784",
    "Name": "Skink Crew",
    "Type": "Statline",
    "Attributes": {
      "M": null,
      "WS": "2",
      "BS": "3",
      "S": "3",
      "T": null,
      "W": null,
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_785",
    "Name": "Skink Priest",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "2",
      "BS": "3",
      "S": "3",
      "T": "2",
      "W": "2",
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_786",
    "Name": "Ancient Stegadon",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": null,
      "S": "6",
      "T": "6",
      "W": "5",
      "I": "1",
      "A": "3",
      "LD": "6"
    }
  },
  {
    "Id": "statline_787",
    "Name": "Coatl",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": null,
      "S": "5",
      "T": "5",
      "W": "5",
      "I": "2",
      "A": "4",
      "LD": "8"
    }
  },
  {
    "Id": "statline_788",
    "Name": "Tiktaq'to",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "4",
      "BS": "5",
      "S": "4",
      "T": "3",
      "W": "2",
      "I": "6",
      "A": "3",
      "LD": "7"
    }
  },
  {
    "Id": "statline_789",
    "Name": "Zwup",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "",
      "S": "4",
      "T": "3",
      "W": "2",
      "I": "2",
      "A": "1",
      "LD": "3"
    }
  },
  {
    "Id": "statline_790",
    "Name": "Cold One Rider",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "",
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "2",
      "A": "2",
      "LD": "8"
    }
  },
  {
    "Id": "statline_791",
    "Name": "Jungle Swarm",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "3",
      "BS": "",
      "S": "2",
      "T": "2",
      "W": "6",
      "I": "1",
      "A": "6",
      "LD": "3"
    }
  },
  {
    "Id": "statline_792",
    "Name": "Saurus Warrior",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "",
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "1",
      "A": "2",
      "LD": "8"
    }
  },
  {
    "Id": "statline_793",
    "Name": "Skink",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "2",
      "BS": "3",
      "S": "3",
      "T": "2",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_794",
    "Name": "Skink Skirmisher",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "2",
      "BS": "3",
      "S": "3",
      "T": "2",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_795",
    "Name": "Chameleon Skink",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "2",
      "BS": "4",
      "S": "3",
      "T": "2",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_796",
    "Name": "Great Crested Skink",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "2",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "6"
    }
  },
  {
    "Id": "statline_797",
    "Name": "Horned One",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "3",
      "BS": "",
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "2",
      "LD": "3"
    }
  },
  {
    "Id": "statline_798",
    "Name": "Kroxigor",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "1",
      "A": "3",
      "LD": "7"
    }
  },
  {
    "Id": "statline_799",
    "Name": "Razordon",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "3",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "4",
      "A": "2",
      "LD": "4"
    }
  },
  {
    "Id": "statline_800",
    "Name": "Ripperdactyl Rider",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "2",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "6"
    }
  },
  {
    "Id": "statline_801",
    "Name": "Ripperdactyl",
    "Type": "Statline",
    "Attributes": {
      "M": "2",
      "WS": "3",
      "BS": "",
      "S": "4",
      "T": "3",
      "W": "2",
      "I": "3",
      "A": "2",
      "LD": "3"
    }
  },
  {
    "Id": "statline_802",
    "Name": "Salamander",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "3",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "4",
      "A": "2",
      "LD": "4"
    }
  },
  {
    "Id": "statline_803",
    "Name": "Temple Guard",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "",
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "2",
      "A": "2",
      "LD": "8"
    }
  },
  {
    "Id": "statline_804",
    "Name": "Terradon Rider",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "2",
      "BS": "3",
      "S": "3",
      "T": "2",
      "W": "1",
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_805",
    "Name": "Bastiladon",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "",
      "S": "5",
      "T": "6",
      "W": "5",
      "I": "1",
      "A": "3",
      "LD": "6"
    }
  },
  {
    "Id": "statline_806",
    "Name": "Skink Crew",
    "Type": "Statline",
    "Attributes": {
      "M": "",
      "WS": "2",
      "BS": "3",
      "S": "3",
      "T": "",
      "W": "",
      "I": "4",
      "A": "1",
      "LD": "5"
    }
  },
  {
    "Id": "statline_807",
    "Name": "Coatl",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "",
      "S": "5",
      "T": "5",
      "W": "5",
      "I": "2",
      "A": "4",
      "LD": "8"
    }
  },
  {
    "Id": "statline_808",
    "Name": "Dread Saurian",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "4",
      "BS": "",
      "S": "8",
      "T": "7",
      "W": "10",
      "I": "1",
      "A": "6",
      "LD": "6"
    }
  }
]

=== Jucyliana/WDS2.0/TOW/Wood Elf Realms - Orion's Wild Hunt/statlines.json
[
  {
    "Id": "statline_868",
    "Name": "Beast Keeper",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/High Elf Realms - Chracian Warhost/statlines.json
[
  {
    "Id": "statline_373",
    "Name": "Chracian Chieftain",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "6",
      "BS": "4",
      "S": "4",
      "T": "3",
      "W": "3",
      "I": "5",
      "A": "3",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_374",
    "Name": "Chracian Woodsman",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "4",
      "S": "4",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "1",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "66ca-f1a3-7cc3-723d"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_375",
    "Name": "Chracian Captain",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "4",
      "S": "4",
      "T": "3",
      "W": "1",
      "I": "4",
      "A": "2",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "66ca-f1a3-7cc3-723d"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_376",
    "Name": "Lion Guard",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "6",
      "BS": "4",
      "S": "4",
      "T": "3",
      "W": "1",
      "I": "5",
      "A": "1",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "66ca-f1a3-7cc3-723d"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_377",
    "Name": "Lion Guard Captain",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "6",
      "BS": "4",
      "S": "4",
      "T": "3",
      "W": "1",
      "I": "5",
      "A": "2",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "66ca-f1a3-7cc3-723d"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  }
]
