=== Jucyliana/WDS2.0/schemas/statlines.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Statlines Schema",
  "description": "Schema for statlines.json files containing game attribute statlines",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Id", "Name", "Type"],
    "properties": {
      "Id": {
        "type": "string",
        "description": "Unique identifier for the statline"
      },
      "Name": {
        "type": "string",
        "description": "Name of the statline"
      },
      "Type": {
        "type": "string",
        "enum": ["Statline"],
        "description": "Type indicator for statline entries"
      },
      "Attributes": {
        "type": "object",
        "description": "Object containing game attributes (M, T, SV, W, LD, OC, IS, etc.)",
        "additionalProperties": {
          "type": ["string", "null"]
        }
      },
      "Children": {
        "type": "array",
        "description": "Array of child items (statlines, rules, equipment, etc.)",
        "items": {
          "type": "object",
          "required": ["Id"],
          "properties": {
            "Id": {
              "type": "string",
              "description": "ID of the child item"
            },
            "Info": {
              "type": "string",
              "description": "Optional additional information about the item"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  }
}

=== Jucyliana/WDS2.0/TOW/Realms of Man - Renegade Crowns/statlines.json
[
  {
    "Id": "statline_569",
    "Name": "Mortar",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "-",
      "BS": "-",
      "S": "-",
      "T": "7",
      "W": "3",
      "I": "-",
      "A": "-",
      "Ld": "-"
    },
    "Children": [
      {
        "Id": "2115-8098-83e9-ead7"
      }
    ]
  },
  {
    "Id": "statline_570",
    "Name": "Gun Crew",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "3",
      "I": "3",
      "A": "3",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_571",
    "Name": "Organ Gun",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "-",
      "BS": "-",
      "S": "-",
      "T": "7",
      "W": "3",
      "I": "-",
      "A": "-",
      "Ld": "-"
    },
    "Children": [
      {
        "Id": "5635-efd8-13b6-c841"
      }
    ]
  },
  {
    "Id": "statline_572",
    "Name": "Hireling Outrider",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_573",
    "Name": "Hireling Outrider",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "3",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_574",
    "Name": "Veteran Freeblade",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_575",
    "Name": "Commander (Freeblade Knight)",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_576",
    "Name": "Warhorses",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "3",
      "BS": "-",
      "S": "3",
      "T": "-",
      "W": "-",
      "I": "3",
      "A": "1",
      "Ld": "-"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_577",
    "Name": "Freeblade Knights",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_578",
    "Name": "Sellswords",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "5"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_579",
    "Name": "Officer",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "6"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_580",
    "Name": "Veteran Sellswords",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "5"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_581",
    "Name": "Veteran Officer",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "6"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_582",
    "Name": "Renegade Captain",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "4",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "4",
      "A": "2",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_584",
    "Name": "Renegade Prince",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "6",
      "BS": "4",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "5",
      "A": "3",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/Tomb Kings of Khemri - Mortuary Cult/statlines.json
[
  {
    "Id": "statline_716",
    "Name": "Arch Necrotect",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "3",
      "I": "3",
      "A": "3",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "7505-7edf-c3de-57a6"
      }
    ]
  },
  {
    "Id": "statline_717",
    "Name": "Necroserpent",
    "Type": "Statline",
    "Attributes": {
      "M": "7",
      "WS": "3",
      "BS": "0",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "3",
      "A": "3",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_718",
    "Name": "Venerable Ushabti",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "3",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "2",
      "A": "3",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      },
      {
        "Id": "2c5f-ac49-f54a-1329"
      }
    ]
  },
  {
    "Id": "statline_719",
    "Name": "Venerable Ancient",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "3",
      "S": "5",
      "T": "4",
      "W": "3",
      "I": "2",
      "A": "4",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      },
      {
        "Id": "2c5f-ac49-f54a-1329"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/Beastmen Brayherds - Minotaur Blood Herd/statlines.json
[
  {
    "Id": "statline_49",
    "Name": "Gor",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "2",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "6"
    },
    "Children": [
      {
        "Id": "44c2-f355-d5ed-24d7"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_50",
    "Name": "True-horn",
    "Type": "Statline",
    "Attributes": {
      "M": "5",
      "WS": "4",
      "BS": "2",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "44c2-f355-d5ed-24d7"
      },
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/statlines.json
[
  {
    "Id": "statline_505",
    "Name": "Giant",
    "Type": "Statline",
    "Attributes": {
      "M": "6",
      "WS": "3",
      "BS": "1",
      "S": "6",
      "T": "6",
      "W": "6",
      "I": "2",
      "A": "*",
      "Ld": "10"
    },
    "Children": [
      {
        "Id": "742-e3dd-26f9-778f"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_559",
    "Name": "Snotling Crew",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "2",
      "BS": "2",
      "S": "2",
      "T": "-",
      "W": "-",
      "I": "3",
      "A": "1",
      "Ld": "4"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "eee5-db12-1271-f2c5"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/40k/Raven Guard/statlines.json
[
  {
    "Id": "statline_3101",
    "Name": "Kayvaan Shrike",
    "Type": "Statline",
    "Attributes": {
      "M": "12\"",
      "T": "4",
      "SV": "3+",
      "W": "5",
      "LD": "6+",
      "OC": "1"
    }
  },
  {
    "Id": "statline_3102",
    "Name": "Aethon Shaan",
    "Type": "Statline",
    "Attributes": {
      "M": "14\"",
      "T": "4",
      "SV": "3",
      "W": "5",
      "LD": "6",
      "OC": "1"
    }
  },
  {
    "Id": "statline_3103",
    "Name": "Blackout",
    "Type": "Statline",
    "Attributes": {
      "Range": "18\"",
      "A": "2",
      "BS": "2+",
      "S": "5",
      "AP": "-1",
      "D": "2"
    }
  },
  {
    "Id": "statline_3104",
    "Name": "The Raven's Talons",
    "Type": "Statline",
    "Attributes": {
      "Range": "Melee",
      "A": "7",
      "WS": "2+",
      "S": "5",
      "AP": "-2",
      "D": "2"
    }
  },
  {
    "Id": "statline_3105",
    "Name": "Claws of Severax",
    "Type": "Statline",
    "Attributes": {
      "Range": "Melee",
      "A": "7",
      "WS": "2+",
      "S": "5",
      "AP": "-2",
      "D": "2"
    }
  },
  {
    "Id": "statline_3106",
    "Name": "Heavy bolt pistol",
    "Type": "Statline",
    "Attributes": {
      "Range": "18\"",
      "A": "1",
      "BS": "2+",
      "S": "4",
      "AP": "-1",
      "D": "1"
    }
  }
]

=== Jucyliana/WDS2.0/TOW/Kingdom of Bretonnia/statlines.json
[
  {
    "Id": "statline_403",
    "Name": "Grail Monk",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "2",
      "BS": "2",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "2",
      "A": "2",
      "Ld": "6"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "e7c7-b48f-7d2c-b337",
        "Info": "(Double-handed)"
      },
      {
        "Id": "985a-110b-3393-79b7",
        "Info": "(Single handed)"
      },
      {
        "Id": "8997-c74d-3a8d-ecf9"
      }
    ]
  },
  {
    "Id": "statline_406",
    "Name": "First Knight",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "4",
      "BS": "2",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "8"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      },
      {
        "Id": "3520-64c9-a855-ce9e"
      },
      {
        "Id": "8997-c74d-3a8d-ecf9"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/Dwarfen Mountain Holds - Slayer Host/statlines.json
[
  {
    "Id": "statline_267",
    "Name": "Shrine Guards",
    "Type": "Statline",
    "Attributes": {
      "M": "3",
      "WS": "5",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "10"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_268",
    "Name": "Shrine Keeper (Shrine Guard)",
    "Type": "Statline",
    "Attributes": {
      "M": "3",
      "WS": "6",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "3",
      "A": "2",
      "Ld": "10"
    }
  },
  {
    "Id": "statline_269",
    "Name": "Imperial Dwarf Warrior",
    "Type": "Statline",
    "Attributes": {
      "M": "3",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "2",
      "A": "2",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  }
]

=== Jucyliana/WDS2.0/TOW/Grand Cathay - Jade Fleet/statlines.json
[
  {
    "Id": "statline_293",
    "Name": "Dragon Company trooper",
    "Type": "Statline",
    "Attributes": {
      "M": "3",
      "WS": "4",
      "BS": "3",
      "S": "3",
      "T": "4",
      "W": "1",
      "I": "2",
      "A": "1",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "3f0e-1dc6-b425-bf59"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "8997-c74d-3a8d-ecf9"
      },
      {
        "Id": "bcf8-d942-102e-b155"
      }
    ]
  },
  {
    "Id": "statline_294",
    "Name": "Captain of the Empire",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "5",
      "BS": "5",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "4",
      "A": "2",
      "Ld": "9"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_295",
    "Name": "Master Mage",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "2",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "3c27-d55d-e778-cb89"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_296",
    "Name": "Priest of Sigmar",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "4",
      "A": "2",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      }
    ]
  },
  {
    "Id": "statline_297",
    "Name": "Priest of Ulric",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "4",
      "BS": "3",
      "S": "4",
      "T": "4",
      "W": "2",
      "I": "4",
      "A": "2",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_298",
    "Name": "State Trooper",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "85-9154-7dc1-ddc6"
      }
    ]
  },
  {
    "Id": "statline_299",
    "Name": "Sargeant",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "dbb2-4d85-84c2-528c"
      },
      {
        "Id": "85-9154-7dc1-ddc6"
      }
    ]
  },
  {
    "Id": "statline_300",
    "Name": "State Missile Trooper",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "1ef1-8579-c310-4fb5"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_301",
    "Name": "Sergeant",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "1ef1-8579-c310-4fb5"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_302",
    "Name": "Militia Fighter",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "6"
    },
    "Children": [
      {
        "Id": "eee5-db12-1271-f2c5"
      },
      {
        "Id": "9bc5-ae1d-c50c-3442"
      }
    ]
  },
  {
    "Id": "statline_303",
    "Name": "Militia Leader",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "2",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "eee5-db12-1271-f2c5"
      },
      {
        "Id": "9bc5-ae1d-c50c-3442"
      }
    ]
  },
  {
    "Id": "statline_304",
    "Name": "Archer",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "d6b8-1ad9-d024-1d72"
      }
    ]
  },
  {
    "Id": "statline_305",
    "Name": "Marksman",
    "Type": "Statline",
    "Attributes": {
      "M": "4",
      "WS": "3",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "d6b8-1ad9-d024-1d72"
      }
    ]
  },
  {
    "Id": "statline_306",
    "Name": "Pistolier",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "3",
      "BS": "3",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "6"
    },
    "Children": [
      {
        "Id": "3f0e-1dc6-b425-bf59"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_307",
    "Name": "Empire Warhorse",
    "Type": "Statline",
    "Attributes": {
      "M": "8",
      "WS": "3",
      "BS": "-",
      "S": "3",
      "T": "-",
      "W": "-",
      "I": "3",
      "A": "1",
      "Ld": "-"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      }
    ]
  },
  {
    "Id": "statline_308",
    "Name": "Veteran",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "3",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "3f0e-1dc6-b425-bf59"
      },
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "b8f7-c4e5-2793-bc18"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      }
    ]
  },
  {
    "Id": "statline_309",
    "Name": "Outriders",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "3",
      "BS": "4",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      },
      {
        "Id": "4c62-cdd4-4e0c-4265"
      },
      {
        "Id": "7f58-91d4-ee6c-3cb7"
      }
    ]
  },
  {
    "Id": "statline_310",
    "Name": "Sharpshooter",
    "Type": "Statline",
    "Attributes": {
      "M": "-",
      "WS": "3",
      "BS": "5",
      "S": "3",
      "T": "3",
      "W": "1",
      "I": "3",
      "A": "1",
      "Ld": "7"
    },
    "Children": [
      {
        "Id": "3f0e-1dc6-b425-bf59"
      },
      {
        "Id": "5f1c-fd04-b0d5-d5e"
      },
      {
        "Id": "6d4a-7733-d725-a267"
      },
      {
        "Id": "c56e-8d1b-bb4-de99"
      },
      {
        "Id": "4c62-cdd4-4e0c-4265"
      },
      {
        "Id": "7f58-91d4-ee6c-3cb7"
      }
    ]
  }
]
